// ================= DATOS: PREGUNTAS =================

const preguntas = {
    laboral: {
        1: [
            "¿Qué es lo que realmente te gusta de tu trabajo, aunque sea un detalle mínimo?",
            "Si pudieras cambiar una sola cosa de tu trabajo, ¿cuál sería y por qué?",
            "¿Qué preferís: un jefe exigente y justo, o relajado pero desorganizado?",
            "Cuando tenés que hacer algo que no querés, ¿cómo buscás la forma de evitarlo?",
            "¿Qué situación laboral te estresa más seguido?",
            "En el trabajo, ¿sos más de seguir reglas o de encontrar “tu manera” de resolver las cosas?",
            "Si mañana no necesitaras trabajar, ¿qué elegirías hacer con tu tiempo?",
            "¿Te cuesta decir “no” cuando te cargan con tareas extra?",
            "¿Cómo describirías tu rol en el equipo (el que apoya, el que calma, el que organiza, el que pone humor)?",
            "¿Qué problema laboral llevás a la cama más de lo que te gustaría admitir?",
            "¿Sentís que tu trabajo actual te representa… o es solo un puente hacia otra cosa?",
            "¿Qué fue lo más injusto que viste en un trabajo sin dar nombres?",
            "Si tu trabajo fuera una persona, ¿qué relación tendrías con él/ella?",
            "¿Qué parte de tu rutina laboral desearías que tu pareja vea para entenderte mejor?",
            "¿Qué habilidad tuya pasa desapercibida en tu trabajo?",
            "¿Preferís estabilidad laboral o desafíos constantes? ¿Por qué?",
            "¿Improvisaste alguna vez en el trabajo fingiendo que sabías algo? ¿Cómo salió?",
            "¿Qué ritual usás para desconectar al llegar a casa?",
            "¿Qué fue lo último que te hizo reír en el trabajo?",
            "¿Qué pensaría tu yo de hace 10 años si viera dónde trabajás hoy?",
            "¿Qué tarea realizás en 'piloto automático' y te gustaría hacer con más consciencia?",
            "¿Cuál es el momento exacto del día en que sentís que tu energía laboral está al 100%?",
            "¿Qué consejo laboral le darías a tu yo más joven?",
            "¿Qué parte de tu trabajo te hace sentir más competente?",
            "¿Qué hábito laboral te gustaría incorporar para mejorar tu productividad?",
            "¿Qué pequeño gesto de un compañero de trabajo te alegró el día recientemente?"
        ],
        2: [
            "¿En qué momento sentiste que elegiste tu camino laboral?",
            "¿Qué frustración laboral todavía recordás como un aprendizaje fuerte?",
            "¿Qué parte de tu personalidad sentís que no podés mostrar en el trabajo?",
            "¿Qué contradicción interna te genera tu profesión?",
            "¿Alguna vez te sentiste estancado? ¿Qué hiciste al respecto?",
            "¿Qué exageración o mentira dijiste en una entrevista laboral y te funcionó?",
            "¿Qué persona en tu trabajo te inspira, aunque no se lo digas?",
            "¿Qué crítica laboral te cuesta aceptar?",
            "¿Qué decisión laboral fue la más difícil de tu vida?",
            "¿Qué sueño laboral dejaste de lado y todavía te duele?",
            "¿Qué te motiva realmente a trabajar: necesidad, reconocimiento, estabilidad, ambición?",
            "¿Viviste alguna vez la sensación de “no pertenecer” en un ambiente laboral?",
            "¿Qué parte de tu trabajo afecta más tu autoestima?",
            "¿Qué injusticia laboral nunca llegaste a procesar del todo?",
            "¿Qué rasgo tuyo te detiene profesionalmente?",
            "¿Qué es lo más difícil de trabajar con otras personas?",
            "¿Qué miedo laboral te acompaña desde hace años?",
            "Si tu jefe pudiera leer tus pensamientos sobre el trabajo, ¿qué cambiaría?",
            "¿Qué parte de tu vida laboral desearías que tu pareja entienda mejor?",
            "¿Cuál fue la última vez que te sentiste realmente orgulloso de tu trabajo?",
            "¿Alguna vez te arrepentiste inmediatamente de aceptar (o rechazar) una oferta laboral? ¿Qué te hizo dudar?",
            "¿Qué parte de tu vida laboral te cuesta más defender o explicar a tu círculo de amigos o familiares?",
            "¿Qué persona en el trabajo te resultó una decepción y por qué?",
            "¿Qué persona te gustaría tener mejor feedback laboral y por qué?",
            "¿Qué tipo de conflicto o situación laboral hace que automáticamente te pongas a la defensiva?",
            "¿Sentís que tu salario actual es un reflejo justo de tu esfuerzo y valor, o que debería ser un tema de conversación pendiente?"
        ],
        3: [
            "¿Qué parte de tu trabajo te hace sentir que no vivís la vida que realmente querés?",
            "¿Cuál es tu mayor miedo laboral y por qué te cuesta admitirlo?",
            "¿Qué expectativa familiar o social aún pesa sobre tu carrera?",
            "¿Qué verdad dura evitás admitir sobre tu motivación laboral?",
            "¿Qué persona te marcó profundamente en tu vida profesional?",
            "¿Qué renuncia laboral te dejó una herida que aún no cerraste?",
            "¿Qué sueño laboral te avergüenza confesar porque parece demasiado grande?",
            "¿Qué parte de tu identidad laboral te gustaría reconstruir desde cero?",
            "¿Qué envidia profesional te reveló algo importante sobre vos mismo?",
            "¿Qué error laboral todavía arrastrás emocionalmente?",
            "¿Qué parte de vos perdés cuando tu vida gira solo alrededor del trabajo?",
            "¿Qué verdad incómoda te duele admitir sobre cómo tu trabajo afecta tu relación?",
            "¿Qué aspecto de tu carrera impacta más tu valor personal?",
            "¿Qué momento de tu vida fue tu “casi renuncio a todo”?",
            "¿Qué talento no pudiste desarrollar por el ritmo laboral?",
            "¿Qué te impide perseguir la vida profesional que realmente soñás?",
            "¿Qué parte de tu pasado laboral preferís que quede oculta?",
            "Si pudieras decir una verdad sin consecuencias, ¿qué confesarías en el trabajo?",
            "¿Qué inseguridad laboral te gustaría que tu pareja entienda mejor?",
            "¿Qué te asusta imaginar si seguís en el mismo camino durante los próximos 10 años?",
            "Si el éxito profesional tuviera un precio emocional fijo, ¿cuál fue la emoción o relación que tuviste que 'sacrificar' para llegar donde estás?",
            "¿Qué parte de tu personalidad 'abandonaste' en el pasado porque pensaste que no era compatible con el mundo profesional?",
            "¿Qué límite personal dejaste pasar en el trabajo y te gustaría recuperar?",
            "¿Qué mentira o fachada laboral sostenés activamente para mantener tu posición o el respeto de tus colegas?",
            "¿Qué legado (o impacto negativo) de tus padres o figuras de autoridad laborales aún opera en tu forma de trabajar?",
            "¿Qué parte de tu vida laboral te gustaría transformar?",
            "Si tu trabajo actual desapareciera mañana, ¿crees que te costaría conseguir otro similar o te sentirías perdido/a?"
        ],
        // ¿QUÉ HARÍAS?
        4: [
            "¿Qué harías si tu jefe te pide hacer algo ilegal que beneficia enormemente a la empresa, pero te hace participar del dinero sucio?",
            "¿Qué harías si descubres que un colega miente constantemente sobre sus logros para conseguir ascensos, pero es tu amigo cercano?",
            "¿Qué harías si te ofrecen un puesto de ensueño en una empresa con valores opuestos a los tuyos y que afecta negativamente a la sociedad?",
            "¿Qué harías si, por error, te pagan el doble de tu salario por un mes, y nadie en recursos humanos se da cuenta?",
            "¿Qué harías si un grave error tuyo pasa desapercibido, pero sabes que a largo plazo podría costar mucho dinero a la empresa?",
            "¿Qué harías si te hiciste encima en una reunión importante?"
        ]
    },

    vida: {
        1: [
            "¿Qué es lo que más valorás de tus amigos actuales?",
            "¿Qué hábito tuyo de todos los días te da un poco de vergüenza admitir?",
            "¿Qué actividad repetirías todos los días si pudieras?",
            "¿Cuál es la situación más graciosa que viviste con un amigo?",
            "¿Qué gesto simple del día a día te alegra el humor?",
            "¿Cómo sería tu domingo perfecto?",
            "¿Qué tipo de amigo/a sos en un grupo?",
            "¿Qué situación cotidiana te irrita más rápido de lo que debería?",
            "¿Con qué amigo/a tenés la confianza absoluta?",
            "¿Qué cosa te cuesta pedir ayuda en la vida diaria?",
            "¿Qué costumbre rara tenés en tu casa que casi nadie conoce?",
            "¿Qué fue lo último que te hizo llorar de risa?",
            "¿Qué pequeño detalle puede mejorar tu día entero?",
            "¿Te cuesta hacer nuevos amigos o se te da natural?",
            "¿Cuál es tu mentira piadosa más frecuente?",
            "¿Qué impulsividad tuviste en la vida cotidiana que todavía te causa risa?",
            "¿Cómo reaccionás cuando un amigo te decepciona?",
            "¿Qué cosa cotidiana te genera nostalgia?",
            "¿Qué actividad te gustaría hacer más seguido con tu pareja?",
            "¿Qué gesto de amistad te derrite por completo?",
            "¿Cuál es el ritual de la mañana que absolutamente no podés saltarte para empezar bien el día?",
            "Si tuvieras que dejar una nota anónima y cómica en la heladera de tu casa para quienes conviven con vos, ¿qué diría?",
            "¿Qué hábito cotidiano te gustaría eliminar de tu vida?",
            "¿Qué es lo que hacés cuando un plan de último momento se cae y te deja un espacio libre inesperado?",
            "¿Qué creencia sobre vos mismo/a (por ejemplo, 'soy desorganizado/a' o 'soy torpe') te hubiera gustado desaprender antes?",
            "¿Qué tipo de actividad social te agota inmediatamente y por qué?"
        ],
        2: [
            "¿Qué amistad dejaste ir y todavía te duele un poco?",
            "¿Qué parte de tu vida cotidiana te gustaría transformar?",
            "¿Qué comportamiento tuyo en la amistad querés mejorar?",
            "¿Qué verdad nunca dijiste para no herir a un amigo?",
            "¿Qué hábito tuyo sentís que te limita día a día?",
            "¿Qué le envidiás a algún amigo, sinceramente?",
            "¿Qué aprendizaje fuerte te dejó una amistad pasada?",
            "¿Qué parte de tu personalidad pocas personas conocen?",
            "¿Qué discusión tonta te dejó pensando demasiado?",
            "¿Qué promesa personal tenés pendiente en tu vida diaria?",
            "¿Qué amigo influyó más en tu forma de ver la vida?",
            "¿Qué aspecto tuyo te gustaría que tu pareja entienda mejor?",
            "¿Qué error en una amistad te gustaría reparar?",
            "¿Qué parte de tu rutina te genera culpa o contradicción?",
            "¿Qué distancia emocional mantenés con ciertas personas y por qué?",
            "¿Qué momento cotidiano realmente te hace sentir vos mismo/a?",
            "¿Qué límite importante aprendiste gracias a una amistad?",
            "¿Qué parte de tu personalidad solo aparece con amigos íntimos?",
            "¿Qué situación cotidiana te obligó a madurar?",
            "¿Qué lugar ocupa la amistad en tu vida comparado con familia y pareja?",
            "¿Qué te cuesta más perdonar en una amistad o en una relación: la mentira o la indiferencia?",
            "¿Qué te dijeron hace mucho tiempo que te dolió, pero con el tiempo resultó ser una verdad incómoda sobre vos?",
            "¿Qué parte de tu vida cotidiana te gustaría compartir más con tus amigos?",
            "¿Qué miedo tenés respecto a la soledad en tu vida diaria?",
            "¿Qué aspecto de tu vida cotidiana te gustaría que tu círculo cercano entienda mejor?",
            "¿Qué hábito tuyo afecta negativamente tus relaciones y te gustaría cambiar?",
            "¿Qué creencia limitante tienes sobre ti mismo/a que afecta tus relaciones?",
        ],
        3: [
            "¿Qué parte tuya sentís que nadie, ni tus amigos, conoce realmente?",
            "¿Qué herida de una amistad pasada todavía influye en cómo te vinculás?",
            "¿Qué arrepentimiento fuerte tenés en alguna amistad?",
            "¿Qué miedo tenés respecto a perder vínculos importantes?",
            "¿Qué verdad dura de tu vida cotidiana te cuesta admitir?",
            "¿Qué persona te falló tan fuerte que te cambió emocionalmente?",
            "¿Qué rol emocional cumplís en tus amistades y cómo te pesa?",
            "¿Qué necesidad afectiva buscás sin darte cuenta en tus amigos?",
            "¿Qué parte de tu vida ocultás por miedo al juicio?",
            "¿Qué amistad te hubiera gustado conservar y no supiste cómo?",
            "¿Qué patrón repetís en tus vínculos sin entender por qué?",
            "¿Qué soledad cotidiana llevás por dentro que casi nadie percibe?",
            "¿Qué verdad incómoda descubriste sobre vos gracias a una amistad?",
            "¿Qué dolor arrastrás por no sentirte comprendido por tu círculo cercano?",
            "¿Qué relación perdiste por orgullo y te gustaría recuperar?",
            "¿Qué parte tuya se cierra emocionalmente cuando alguien intenta acercarse demasiado?",
            "¿Qué expectativa poco realista ponés en tus amistades?",
            "¿Qué límite dejaste pasar por miedo a estar solo/a?",
            "¿Qué vínculo actual te genera contradicción interna?",
            "¿Qué verdad emocional te gustaría decirle a alguien sin miedo a perderlo?",
            "¿Qué necesidad afectiva que no fue cubierta en tu infancia seguís buscando inconscientemente en tus vínculos adultos?",
            "¿Qué parte de tu identidad sentís que sacrificaste para encajar en ciertos grupos?",
            "¿Qué miedo tenés respecto a mostrar tu vulnerabilidad en tus relaciones cercanas?",
            "¿Qué aspecto de tu vida cotidiana te gustaría transformar radicalmente si no tuvieras miedo al qué dirán?",
            "¿Qué patrón de comportamiento repetís en tus amistades que sabés que te hace daño pero no podés evitar?",
            "¿Qué parte de tu historia personal te cuesta compartir incluso con tus amigos más cercanos?"
        ],
         //¿QUÉ HARÍAS?
        4: [
            "¿Qué harías si, al despertar, descubres que tienes la habilidad de hablar con los pájaros, pero solo te cuentan chismes de otros vecinos?",
            "¿Qué harías si tu refrigerador se convierte en una máquina del tiempo y solo puede viajar 10 minutos al pasado?",
            "¿Qué harías si tu mascota te dice que te odia profundamente, pero que tiene que vivir contigo solo por comida?",
            "¿Qué harías si cada vez que estornudás, cambiás de ropa automáticamente a un atuendo completamente aleatorio, es decir si estas en una fiesta debes explicar que pasó?",
            "¿Qué harías si solo puedes comunicarte con las personas cantando reggaetón hasta que te duermas?"
        ]
    },

    // Vida en pareja: para conocer a fondo a tu pareja.
    // Basado en los "mapas del amor" de Gottman y en la apertura gradual de las 36 preguntas de Aron.
    // Revisado con un sexólogo y terapeuta de pareja: estrés, reparación, espacio propio, rituales, intimidad no explícita y cartas de acción.
    // Los nombres de los niveles están en mazo.js (MAZOS.parejas).
    // Una carta puede ser un texto (toma el tipo del nivel) o un objeto { tipo, texto, tiempo } para las cartas de acción.
    parejas: {
        // ¿CUÁNTO ME CONOCÉS? (quien saca la carta adivina la respuesta de su pareja)
        1: [
            "¿Cuál es la comida favorita de tu pareja? ¿Y cuál no comería nunca?",
            "¿Qué es lo que más rápido saca de quicio a tu pareja?",
            "¿Cómo se llama la persona que fue mejor amiga de tu pareja en la infancia?",
            "¿Qué haría tu pareja con un día libre, sin obligaciones y sin vos?",
            "¿Cuál es el mayor miedo de tu pareja?",
            "¿Qué música escucha tu pareja cuando está triste?",
            "¿Qué quería ser tu pareja de grande cuando era chica o chico?",
            "¿Qué es lo que más estresa a tu pareja en este momento de su vida?",
            "¿Cómo prefiere recibir cariño tu pareja: palabras, regalos, tiempo juntos, ayuda o contacto físico?",
            "¿Qué lugar del mundo se muere por conocer tu pareja?",
            "¿Cuál es, según tu pareja, el mejor regalo que le hiciste?",
            "¿Qué hace tu pareja cuando tiene bronca y no quiere hablar?",
            "¿Qué persona de su familia es la más importante para tu pareja?",
            "¿Cuál es el recuerdo favorito de tu pareja de ustedes dos?",
            "Cuando tu pareja está desbordada, ¿qué necesita: que le des espacio o que te quedes cerca?",
            "¿Cuál es el momento del día juntos que tu pareja más disfruta?",
            "¿Cuál es la manía tuya más absurda que tu pareja ya aprendió a tolerar?"
        ],
        // MI MUNDO (su presente)
        2: [
            "¿Qué es lo que más te ocupa la cabeza esta semana?",
            "¿Qué momento de tu día esperás con más ganas?",
            "Además de mí, ¿con quién es con quien más te gusta hablar y por qué?",
            "¿Hay algo que te esté preocupando y todavía no me contaste?",
            "¿Qué hiciste últimamente que te dio orgullo de vos?",
            "¿Qué cosa chiquita te arruina el día aunque parezca una pavada?",
            "¿Qué actividad o hobby te gustaría retomar o empezar?",
            "¿Qué te recarga las pilas cuando no das más?",
            "¿Cuál es tu momento favorito de nuestra rutina juntos?",
            "¿Qué meta personal tenés este año que no tenga que ver conmigo?",
            "¿Qué te gustaría que te pregunte más seguido cuando llegás a casa?",
            "¿En qué parte de tu vida sentís que necesitás más apoyo ahora?",
            "¿Qué serie, libro o tema te atrapa últimamente?",
            "¿Qué cosa de tu trabajo o de tu estudio te gustaría que yo entienda mejor?",
            "Cuando te desbordás, ¿qué te ayuda a bajar: hablar, moverte, un rato a solas o que te abrace?",
            "¿En qué área de tu vida sentís que necesitás más tiempo o espacio para vos?",
            "¿Qué ritual nuestro de todos los días no querés perder nunca?",
            { tipo: "chequeo", tiempo: null, texto: "Del 1 al 10, ¿cuánto sentiste que te escuché esta semana? ¿Qué sumaría un punto?" },
            { tipo: "chequeo", tiempo: null, texto: "Del 1 al 10, ¿cuánto tiempo de calidad sentís que tuvimos este mes? ¿Qué lo subiría un punto?" },
            "¿Cuál es la manía mía más absurda que ya aprendiste a tolerar?",
            "¿Qué defecto tenemos los dos que, en vez de enojarnos, nos da risa?",
            { tipo: "comodin", tiempo: 60, texto: "Masaje inmediato: recibís un masaje de hombros o de pies y no tenés que responder nada." },
            { tipo: "accion", tiempo: 60, texto: "Contale a tu pareja algo que te pasó hoy. Durante 60 segundos solo escucha, sin opinar ni dar consejos. Al final te abraza." }
        ],
        // MI HISTORIA (sus raíces)
        3: [
            "¿Cómo se demostraba el cariño en tu casa durante tu infancia?",
            "¿Qué recuerdo de tu infancia te sigue haciendo sonreír?",
            "¿Qué momento de tu vida te cambió para siempre?",
            "¿Quién fue la persona que más te marcó mientras crecías y por qué?",
            "¿Cómo se manejaban las peleas en tu familia? ¿Qué repetís y qué no quisiste repetir?",
            "¿Qué aprendiste de tus relaciones anteriores que hoy aplicás con nosotros?",
            "¿Hubo una etapa de tu vida en la que sentiste mucha soledad? ¿Qué te ayudó a salir adelante?",
            "¿Qué te decían en tu infancia que hoy te gustaría dejar atrás? Contá solo lo que tengas ganas.",
            "¿Qué decepción de tu vida te terminó enseñando algo? Contá solo lo que tengas ganas.",
            "¿De qué logro tuyo casi nadie sabe?",
            "¿Qué tradición de tu familia te gustaría que tengamos nosotros?",
            "¿Cómo era tu vida justo antes de conocerme?",
            "¿Qué pensaste la primera vez que me viste? ¿Y cuándo supiste que te gustaba de verdad?",
            "¿Hay algo de tu pasado que te gustaría contarme de a poco, cuando tengas ganas?",
            "¿Cómo se pedían perdón en tu casa? ¿Cómo te gusta que te lo pidan hoy?",
            { tipo: "accion", tiempo: null, texto: "Buscá una foto de tu infancia y mostrásela a tu pareja. Contale qué estaba pasando en tu vida en ese momento." }
        ],
        // PONER A PRUEBA (¿qué harías?): dilemas para ver cómo funcionamos como equipo
        4: [
            "¿Qué harías si tuvieras una deuda que te da vergüenza contarme? ¿Qué necesitarías de mí para animarte a decírmelo?",
            "¿Qué harías si la persona que es tu mejor amistad y tu pareja no se soportan?",
            "¿Qué harías si tu pareja quiere mudarse lejos por su carrera y vos estás bien donde estás?",
            "¿Qué harías si tu familia critica todo el tiempo a tu pareja? ¿Cómo haríamos equipo frente a eso?",
            "¿Qué harías si tu ex te escribe para volver a hablar? ¿Qué límites con el pasado nos hacen sentir seguros a los dos?",
            "¿Qué harías si tu pareja quiere tener hijos ya y vos todavía no?",
            "¿Qué harías si ves sin querer un mensaje en el celular de tu pareja que te genera dudas? ¿Cómo te gustaría que lo hablemos?",
            "¿Qué harían si ganan la lotería mañana? ¿Qué es lo primero que hacen?",
            "¿Qué harías si tu pareja pierde el trabajo y cae en un bajón largo?",
            "¿Qué harías si tu pareja te pide un tiempo?",
            "¿Qué harías si te enterás de que tu pareja le contó a alguien algo muy íntimo tuyo?",
            "¿Qué harías si en una discusión los dos tienen razón y ninguno quiere ceder?",
            "¿Qué harías si discutimos fuerte justo antes de juntarnos con amigos? ¿Cómo lo pausamos y lo retomamos después?"
        ],
        // CORAZÓN ABIERTO (necesidades, miedos, reparación y qué le hace sentir amor)
        5: [
            "¿Cuándo sentís más mi amor? Dame un ejemplo concreto.",
            "Cuando estás triste, ¿qué necesitás de mí: que te hable, que te abrace o que te dé espacio?",
            "¿Hay algo que hago que te lastima y nunca me dijiste?",
            "¿Qué es lo que más miedo te da perder de nuestra relación?",
            "¿En qué momento sentiste que yo no te entendía?",
            "¿Qué te cuesta pedirme?",
            "¿Qué inseguridad tuya te gustaría que conozca para cuidarla mejor?",
            "Cuando peleamos, ¿qué es lo que más te duele que haga o diga?",
            "¿Qué gesto mío te hace sentir en casa?",
            "¿Cómo te das cuenta de que estoy mal aunque no diga nada?",
            "¿Qué te gustaría que te agradezca más seguido?",
            "¿Hay algo de vos que todavía no te animaste a mostrarme?",
            "¿Qué te da celos o inseguridad, y qué acuerdos nos darían tranquilidad a los dos?",
            "¿Qué momento reciente te hizo pensar: «elegí bien»?",
            "Después de una pelea, ¿qué necesitás escuchar de mí para darla por cerrada?",
            "¿Cómo te das cuenta de que estás llegando a tu límite? ¿Qué señal tuya te gustaría que aprenda a leer?",
            "¿Hay algo que te lastimó y sentís que todavía no reparamos?",
            { tipo: "chequeo", tiempo: null, texto: "Del 1 al 10, ¿qué tan en equipo te sentís conmigo hoy? ¿Qué necesitarías para sumar un punto?" },
            { tipo: "comodin", tiempo: null, texto: "Pregunta libre: hacele a tu pareja la pregunta que quieras. Tiene que responder con total honestidad." },
            { tipo: "accion", tiempo: 60, texto: "Mírense a los ojos en silencio durante 60 segundos, sin hablar. Después cuenten qué sintieron." },
            { tipo: "accion", tiempo: null, texto: "Decile a tu pareja 3 cosas concretas que hizo esta semana y que te hicieron la vida más linda." },
            { tipo: "accion", tiempo: 60, texto: "Abrácense durante 60 segundos sin hablar, hasta que sientan que respiran al mismo ritmo." }
        ],
        // INTIMIDAD Y DESEO (comunicación sobre la intimidad, sin contenido explícito)
        6: [
            "¿Qué gesto cotidiano mío te hace sentir deseo de mi parte?",
            "¿Cómo te gusta que te seduzcan fuera de la habitación?",
            "¿Qué tan fácil o difícil te resulta pedirme lo que necesitás en la intimidad?",
            "¿Qué te da comodidad y confianza para disfrutar de la intimidad conmigo?",
            "¿Qué cosas bajan tu deseo: el cansancio, el estrés, la rutina u otra cosa?",
            "¿Sentís que la frecuencia de nuestros encuentros está bien para vos? ¿Qué cambiarías?",
            "¿Cómo te gustaría que nos digamos que no a algo sin que la otra persona sienta rechazo?",
            "¿Cuál es tu caricia favorita que no tiene nada de sexual?",
            "¿Qué aprendiste en tu infancia sobre el cuerpo, el placer o el amor que hoy te gustaría desaprender?",
            "¿Cuál fue el momento en que te sentiste más cerca mío sin que fuera sexual?",
            "¿Qué recuerdo nuestro de intimidad te hace sonreír?",
            { tipo: "comodin", tiempo: null, texto: "Pase con beso: pasás esta carta sin responder, a cambio de un beso a tu pareja." },
            { tipo: "accion", tiempo: null, texto: "Mirando a tu pareja a los ojos, decile qué es lo que más te atrae. Tiene que ser algo que nunca le dijiste." },
            { tipo: "accion", tiempo: 60, texto: "Tómense de las manos y, durante 60 segundos, recorran con los dedos las manos del otro, sin hablar." }
        ],
        // NUESTRO FUTURO (acuerdos, espacio propio y rituales)
        7: [
            "¿Cómo te imaginás un día cualquiera nuestro dentro de 10 años?",
            "¿Querés tener hijos? ¿Cuántos, cuándo y cómo te imaginás criándolos?",
            "¿Dónde te gustaría que vivamos: en la ciudad, en el campo, en otro país?",
            "¿Cómo te gustaría que manejemos la plata: todo junto, todo separado o una mezcla?",
            "¿Qué sueño tuyo necesita de mi apoyo para cumplirse?",
            "¿Cómo te imaginás nuestra vejez?",
            "¿Qué es lo que nunca negociarías en una relación?",
            "¿Qué viaje tenemos que hacer sí o sí en los próximos cinco años?",
            "Según vos, ¿cómo sería un reparto justo de las tareas de la casa?",
            "¿Qué lugar querés que ocupen nuestras familias en nuestra vida?",
            "Si mañana te ofrecen el trabajo soñado en otro país, ¿cómo lo decidiríamos?",
            "¿Qué tradición inventamos para festejar nuestro aniversario?",
            "¿Qué te gustaría que digan de nosotros como pareja dentro de muchos años?",
            "¿Qué hábito podríamos empezar juntos para cuidar la relación?",
            "¿Cómo cuidamos el tiempo de cada uno sin que el otro lo sienta como distancia?",
            "¿Cómo te gustaría que nos saludemos y nos despidamos cada día?",
            "¿Qué acuerdo nos ayudaría a pelear mejor: pausar, no gritar, no irnos a dormir enojados?",
            "¿Qué acuerdos hacen que sientas que nuestro vínculo es un lugar seguro?",
            { tipo: "comodin", tiempo: null, texto: "Antojo: elegí algo rico que tu pareja te prepare o te traiga esta semana." },
            { tipo: "accion", tiempo: null, texto: "Escriban cada uno en el celular un deseo para la pareja este año. Léanlos en voz alta al mismo tiempo." }
        ],
        // CIERRE (una al azar al terminar el mazo, para cerrar en positivo)
        cierre: [
            "Decile a tu pareja algo que respondió hoy que te hizo sentir amor, admiración o alivio.",
            "Tómense de las manos, mírense durante 3 respiraciones profundas y dense un beso de 5 segundos.",
            "¿Qué plan chiquito y simple nos gustaría hacer juntos esta misma semana?"
        ]
    }
};
