// ================= DATOS: PREGUNTAS =================

const preguntas = {
    laboral: {
        1: [
            "¿Qué es lo que realmente te gusta de tu trabajo, aunque sea un detalle mínimo?",
            "Si pudieras cambiar una sola cosa de tu trabajo, ¿cuál sería y por qué?",
            "¿Qué preferís: un jefe exigente y justo, o relajado pero desorganizado?",
            "Cuando tenés que hacer algo que no querés, ¿cómo buscás la forma de evitarlo?",
            "¿Qué situación laboral te estresa más seguido?",
            "En el trabajo, ¿sos más de seguir reglas o de encontrar “tu manera” de resolver las cosas?",
            "Si mañana no necesitaras trabajar, ¿qué elegirías hacer con tu tiempo?",
            "¿Te cuesta decir “no” cuando te cargan con tareas extra?",
            "¿Cómo describirías tu rol en el equipo (el que apoya, el que calma, el que organiza, el que pone humor)?",
            "¿Qué problema laboral llevás a la cama más de lo que te gustaría admitir?",
            "¿Sentís que tu trabajo actual te representa… o es solo un puente hacia otra cosa?",
            "¿Qué fue lo más injusto que viste en un trabajo sin dar nombres?",
            "Si tu trabajo fuera una persona, ¿qué relación tendrías con él/ella?",
            "¿Qué parte de tu rutina laboral desearías que tu pareja vea para entenderte mejor?",
            "¿Qué habilidad tuya pasa desapercibida en tu trabajo?",
            "¿Preferís estabilidad laboral o desafíos constantes? ¿Por qué?",
            "¿Improvisaste alguna vez en el trabajo fingiendo que sabías algo? ¿Cómo salió?",
            "¿Qué ritual usás para desconectar al llegar a casa?",
            "¿Qué fue lo último que te hizo reír en el trabajo?",
            "¿Qué pensaría tu yo de hace 10 años si viera dónde trabajás hoy?",
            "¿Qué tarea realizás en 'piloto automático' y te gustaría hacer con más consciencia?",
            "¿Cuál es el momento exacto del día en que sentís que tu energía laboral está al 100%?",
            "¿Qué consejo laboral le darías a tu yo más joven?",
            "¿Qué parte de tu trabajo te hace sentir más competente?",
            "¿Qué hábito laboral te gustaría incorporar para mejorar tu productividad?",
            "¿Qué pequeño gesto de un compañero de trabajo te alegró el día recientemente?"
        ],
        2: [
            "¿En qué momento sentiste que elegiste tu camino laboral?",
            "¿Qué frustración laboral todavía recordás como un aprendizaje fuerte?",
            "¿Qué parte de tu personalidad sentís que no podés mostrar en el trabajo?",
            "¿Qué contradicción interna te genera tu profesión?",
            "¿Alguna vez te sentiste estancado? ¿Qué hiciste al respecto?",
            "¿Qué exageración o mentira dijiste en una entrevista laboral y te funcionó?",
            "¿Qué persona en tu trabajo te inspira, aunque no se lo digas?",
            "¿Qué crítica laboral te cuesta aceptar?",
            "¿Qué decisión laboral fue la más difícil de tu vida?",
            "¿Qué sueño laboral dejaste de lado y todavía te duele?",
            "¿Qué te motiva realmente a trabajar: necesidad, reconocimiento, estabilidad, ambición?",
            "¿Viviste alguna vez la sensación de “no pertenecer” en un ambiente laboral?",
            "¿Qué parte de tu trabajo afecta más tu autoestima?",
            "¿Qué injusticia laboral nunca llegaste a procesar del todo?",
            "¿Qué rasgo tuyo te detiene profesionalmente?",
            "¿Qué es lo más difícil de trabajar con otras personas?",
            "¿Qué miedo laboral te acompaña desde hace años?",
            "Si tu jefe pudiera leer tus pensamientos sobre el trabajo, ¿qué cambiaría?",
            "¿Qué parte de tu vida laboral desearías que tu pareja entienda mejor?",
            "¿Cuál fue la última vez que te sentiste realmente orgulloso de tu trabajo?",
            "¿Alguna vez te arrepentiste inmediatamente de aceptar (o rechazar) una oferta laboral? ¿Qué te hizo dudar?",
            "¿Qué parte de tu vida laboral te cuesta más defender o explicar a tu círculo de amigos o familiares?",
            "¿Qué persona en el trabajo te resultó una decepción y por qué?",
            "¿Qué persona te gustaría tener mejor feedback laboral y por qué?",
            "¿Qué tipo de conflicto o situación laboral hace que automáticamente te pongas a la defensiva?",
            "¿Sentís que tu salario actual es un reflejo justo de tu esfuerzo y valor, o que debería ser un tema de conversación pendiente?"
        ],
        3: [
            "¿Qué parte de tu trabajo te hace sentir que no vivís la vida que realmente querés?",
            "¿Cuál es tu mayor miedo laboral y por qué te cuesta admitirlo?",
            "¿Qué expectativa familiar o social aún pesa sobre tu carrera?",
            "¿Qué verdad dura evitás admitir sobre tu motivación laboral?",
            "¿Qué persona te marcó profundamente en tu vida profesional?",
            "¿Qué renuncia laboral te dejó una herida que aún no cerraste?",
            "¿Qué sueño laboral te avergüenza confesar porque parece demasiado grande?",
            "¿Qué parte de tu identidad laboral te gustaría reconstruir desde cero?",
            "¿Qué envidia profesional te reveló algo importante sobre vos mismo?",
            "¿Qué error laboral todavía arrastrás emocionalmente?",
            "¿Qué parte de vos perdés cuando tu vida gira solo alrededor del trabajo?",
            "¿Qué verdad incómoda te duele admitir sobre cómo tu trabajo afecta tu relación?",
            "¿Qué aspecto de tu carrera impacta más tu valor personal?",
            "¿Qué momento de tu vida fue tu “casi renuncio a todo”?",
            "¿Qué talento no pudiste desarrollar por el ritmo laboral?",
            "¿Qué te impide perseguir la vida profesional que realmente soñás?",
            "¿Qué parte de tu pasado laboral preferís que quede oculta?",
            "Si pudieras decir una verdad sin consecuencias, ¿qué confesarías en el trabajo?",
            "¿Qué inseguridad laboral te gustaría que tu pareja entienda mejor?",
            "¿Qué te asusta imaginar si seguís en el mismo camino durante los próximos 10 años?",
            "Si el éxito profesional tuviera un precio emocional fijo, ¿cuál fue la emoción o relación que tuviste que 'sacrificar' para llegar donde estás?",
            "¿Qué parte de tu personalidad 'abandonaste' en el pasado porque pensaste que no era compatible con el mundo profesional?",
            "¿Qué límite personal dejaste pasar en el trabajo y te gustaría recuperar?",
            "¿Qué mentira o fachada laboral sostenés activamente para mantener tu posición o el respeto de tus colegas?",
            "¿Qué legado (o impacto negativo) de tus padres o figuras de autoridad laborales aún opera en tu forma de trabajar?",
            "¿Qué parte de tu vida laboral te gustaría transformar?",
            "Si tu trabajo actual desapareciera mañana, ¿qué te costaría más perder: el título, el dinero, o la identidad que te da?"
        ]
    },

    vida: {
        1: [
            "¿Qué es lo que más valorás de tus amigos actuales?",
            "¿Qué hábito tuyo de todos los días te da un poco de vergüenza admitir?",
            "¿Qué actividad repetirías todos los días si pudieras?",
            "¿Cuál es la situación más graciosa que viviste con un amigo?",
            "¿Qué gesto simple del día a día te alegra el humor?",
            "¿Cómo sería tu domingo perfecto?",
            "¿Qué tipo de amigo/a sos en un grupo?",
            "¿Qué situación cotidiana te irrita más rápido de lo que debería?",
            "¿Con qué amigo/a tenés la confianza absoluta?",
            "¿Qué cosa te cuesta pedir ayuda en la vida diaria?",
            "¿Qué costumbre rara tenés en tu casa que casi nadie conoce?",
            "¿Qué fue lo último que te hizo llorar de risa?",
            "¿Qué pequeño detalle puede mejorar tu día entero?",
            "¿Te cuesta hacer nuevos amigos o se te da natural?",
            "¿Cuál es tu mentira piadosa más frecuente?",
            "¿Qué impulsividad tuviste en la vida cotidiana que todavía te causa risa?",
            "¿Cómo reaccionás cuando un amigo te decepciona?",
            "¿Qué cosa cotidiana te genera nostalgia?",
            "¿Qué actividad te gustaría hacer más seguido con tu pareja?",
            "¿Qué gesto de amistad te derrite por completo?",
            "¿Cuál es el ritual de la mañana que absolutamente no podés saltarte para empezar bien el día?",
            "Si tuvieras que dejar una nota anónima y cómica en la heladera de tu casa para quienes conviven con vos, ¿qué diría?",
            "¿Qué hábito cotidiano te gustaría eliminar de tu vida?",
            "¿Qué es lo que hacés cuando un plan de último momento se cae y te deja un espacio libre inesperado?",
            "¿Qué creencia sobre vos mismo/a (por ejemplo, 'soy desorganizado/a' o 'soy torpe') te hubiera gustado desaprender antes?",
            "¿Qué tipo de actividad social te agota inmediatamente y por qué?"
        ],
        2: [
            "¿Qué amistad dejaste ir y todavía te duele un poco?",
            "¿Qué parte de tu vida cotidiana te gustaría transformar?",
            "¿Qué comportamiento tuyo en la amistad querés mejorar?",
            "¿Qué verdad nunca dijiste para no herir a un amigo?",
            "¿Qué hábito tuyo sentís que te limita día a día?",
            "¿Qué le envidiás a algún amigo, sinceramente?",
            "¿Qué aprendizaje fuerte te dejó una amistad pasada?",
            "¿Qué parte de tu personalidad pocas personas conocen?",
            "¿Qué discusión tonta te dejó pensando demasiado?",
            "¿Qué promesa personal tenés pendiente en tu vida diaria?",
            "¿Qué amigo influyó más en tu forma de ver la vida?",
            "¿Qué aspecto tuyo te gustaría que tu pareja entienda mejor?",
            "¿Qué error en una amistad te gustaría reparar?",
            "¿Qué parte de tu rutina te genera culpa o contradicción?",
            "¿Qué distancia emocional mantenés con ciertas personas y por qué?",
            "¿Qué momento cotidiano realmente te hace sentir vos mismo/a?",
            "¿Qué límite importante aprendiste gracias a una amistad?",
            "¿Qué parte de tu personalidad solo aparece con amigos íntimos?",
            "¿Qué situación cotidiana te obligó a madurar?",
            "¿Qué lugar ocupa la amistad en tu vida comparado con familia y pareja?",
            "¿Qué te cuesta más perdonar en una amistad o en una relación: la mentira o la indiferencia?",
            "¿Qué te dijeron hace mucho tiempo que te dolió, pero con el tiempo resultó ser una verdad incómoda sobre vos?",
            "¿Qué parte de tu vida cotidiana te gustaría compartir más con tus amigos?",
            "¿Qué miedo tenés respecto a la soledad en tu vida diaria?",
            "¿Qué aspecto de tu vida cotidiana te gustaría que tu círculo cercano entienda mejor?",
            "¿Qué hábito tuyo afecta negativamente tus relaciones y te gustaría cambiar?"
        ],
        3: [
            "¿Qué parte tuya sentís que nadie, ni tus amigos, conoce realmente?",
            "¿Qué herida de una amistad pasada todavía influye en cómo te vinculás?",
            "¿Qué arrepentimiento fuerte tenés en alguna amistad?",
            "¿Qué miedo tenés respecto a perder vínculos importantes?",
            "¿Qué verdad dura de tu vida cotidiana te cuesta admitir?",
            "¿Qué persona te falló tan fuerte que te cambió emocionalmente?",
            "¿Qué rol emocional cumplís en tus amistades y cómo te pesa?",
            "¿Qué necesidad afectiva buscás sin darte cuenta en tus amigos?",
            "¿Qué parte de tu vida ocultás por miedo al juicio?",
            "¿Qué amistad te hubiera gustado conservar y no supiste cómo?",
            "¿Qué patrón repetís en tus vínculos sin entender por qué?",
            "¿Qué soledad cotidiana llevás por dentro que casi nadie percibe?",
            "¿Qué verdad incómoda descubriste sobre vos gracias a una amistad?",
            "¿Qué dolor arrastrás por no sentirte comprendido por tu círculo cercano?",
            "¿Qué relación perdiste por orgullo y te gustaría recuperar?",
            "¿Qué parte tuya se cierra emocionalmente cuando alguien intenta acercarse demasiado?",
            "¿Qué expectativa poco realista ponés en tus amistades?",
            "¿Qué límite dejaste pasar por miedo a estar solo/a?",
            "¿Qué vínculo actual te genera contradicción interna?",
            "¿Qué verdad emocional te gustaría decirle a alguien sin miedo a perderlo?",
            "¿Qué necesidad afectiva que no fue cubierta en tu infancia seguís buscando inconscientemente en tus vínculos adultos?",
            "¿Qué parte de tu identidad sentís que sacrificaste para encajar en ciertos grupos?",
            "¿Qué miedo tenés respecto a mostrar tu vulnerabilidad en tus relaciones cercanas?",
            "¿Qué aspecto de tu vida cotidiana te gustaría transformar radicalmente si no tuvieras miedo al qué dirán?",
            "¿Qué patrón de comportamiento repetís en tus amistades que sabés que te hace daño pero no podés evitar?"
        ]
    },

    parejas: {
        1: [
            "¿Qué parte del cuerpo te gusta más que tu pareja explore?",
            "¿Qué prenda te hace sentir más atractivo/a?",
            "¿Qué gesto o mirada te activa el deseo automáticamente?",
            "¿Qué parte del cuerpo de tu pareja te resulta más irresistible?",
            "¿Preferís conectar con calma o con intensidad? ¿Por qué?",
            "¿Qué señal usás cuando querés un momento íntimo?",
            "¿Qué tipo de caricia te relaja y te enciende al mismo tiempo?",
            "¿Qué recuerdo sensual compartido tenés guardado?",
            "¿Qué ambiente te despierta más deseo (luz, música, silencio...)?",
            "¿Qué fantasía ligera te genera curiosidad?",
            "¿Qué aroma o sensación te pone en modo “romántico/sensual”?",
            "¿Qué detalle mínimo de tu pareja te activa muchísimo?",
            "¿Te gusta más iniciar o que inicien contigo?",
            "¿Qué prenda te encanta que tu pareja use?",
            "¿Qué tipo de anticipación te excita más: palabras, miradas o roces?",
            "¿Qué caricia simple sabés que siempre funciona contigo?",
            "¿Qué actitud segura de tu pareja te resulta irresistible?",
            "¿Qué situación cotidiana te sorprende cuando te despierta deseo?",
            "¿Te gusta más la complicidad previa o el momento en sí?",
            "¿Qué fantasía “suave” te gustaría que tu pareja descubra sin que se la digas?",
            "¿Qué tipo de mirada (larga, juguetona, profunda) de tu pareja es tu lenguaje de deseo favorito?",
            "¿Cuál es el momento del día o la noche en que te sentís más sexy y por qué?",
            "¿Qué gesto inesperado de tu pareja te hace sentir deseado/a al instante?",
            "¿Qué tipo de caricia (suave, firme, lenta, rápida) te enciende más rápido?",
            "¿Qué lugar inusual te gustaría explorar con tu pareja para un momento íntimo?"
        ],
        2: [
            "¿Qué fantasía te da curiosidad pero nunca dijiste por pudor?",
            "¿Qué tipo de rol te intriga explorar con tu pareja?",
            "¿Qué límite suave te gustaría correr un poco más?",
            "¿Qué te excita más: la sensación de controlar o la de entregarte?",
            "¿Qué pensamiento “incorrecto” te sorprendió alguna vez?",
            "¿Qué te gustaría que tu pareja te pida con seguridad?",
            "¿Qué te genera deseo aunque te da un poco de vergüenza admitirlo?",
            "¿Qué tipo de tensión psicológica te enciende?",
            "¿Qué fantasía recurrente aparece en tu cabeza?",
            "¿Qué te hace sentir vulnerable de forma erótica?",
            "¿Qué parte de tu personalidad aparece cuando sentís mucho deseo?",
            "¿Qué situación de la vida real te prende inesperadamente?",
            "¿Qué cosa te gustaría explorar sin ir demasiado lejos?",
            "¿Qué te gustaría que tu pareja intuya de vos en lo íntimo?",
            "¿Qué elogio sensual te derrite por completo?",
            "¿Qué te da más miedo admitir: un deseo o una fantasía?",
            "¿Qué gesto provocador de tu pareja te desestabiliza mentalmente?",
            "¿Qué juego psicológico te genera curiosidad?",
            "¿Qué aspecto de vos mismo te gustaría liberar más en lo íntimo?",
            "¿Qué deseo sentís que todavía no encontraste cómo expresar?",
            "¿Qué acto de servicio o atención fuera de lo íntimo te pone mentalmente en 'modo deseo'?",
            "Si pudieras dirigir una escena íntima con tu pareja, ¿qué diálogo o frase usarías para encender la tensión?",
            "¿Qué tipo de atrevimiento de tu pareja (sin cruzar un límite) te sorprendería y excitaría genuinamente?",
            "¿Qué te hace sentir más deseado/a: que te miren intensamente o que te toquen con intención?",
            "¿Qué creencia sobre tu propio cuerpo te gustaría liberar para disfrutar más de la intimidad?"
        ],
        3: [
            "¿Qué deseo interno reprimiste porque temías ser juzgado/a?",
            "¿Qué fantasía te conmueve por lo vulnerable que te hace sentir?",
            "¿Qué escenario prohibido te genera conflicto entre lo que querés y lo que creés correcto?",
            "¿Qué parte de tu sombra sexual te gustaría comprender mejor?",
            "¿Qué impulso íntimo te sorprendió alguna vez al punto de replantearte cosas?",
            "¿Qué confesión no hiciste nunca por miedo a cambiar la dinámica de la relación?",
            "¿Qué deseo sentís “demasiado intenso” para expresarlo abiertamente?",
            "¿Qué contradicción interna tenés entre deseo y moral?",
            "¿Qué te excita porque te saca de control emocional?",
            "¿Qué secreto sexual guardás desde hace años?",
            "¿Qué límite personal te gustaría explorar sin sentir culpa?",
            "¿Qué recuerdo íntimo marcó tu forma de desear?",
            "¿Qué versión tuya aparece cuando dejás de controlar todo?",
            "¿Qué fantasía temés que revele demasiado sobre tu interior?",
            "¿Qué impulso oculto te asusta que tu pareja descubra?",
            "¿Qué deseo prohibido te hace sentir más vivo/a?",
            "¿Qué miedo tenés respecto a mostrar tu parte más erótica?",
            "¿Qué tema sexual evitás hablar aunque sabés que sería liberador?",
            "¿Qué verdad íntima te gustaría confesar sin consecuencias?",
            "¿Qué parte de tu identidad sexual escondés incluso en pareja?",
            "¿Qué te frustra más de tu propia reacción ante el deseo: la inhibición, el pudor o el miedo al rechazo?",
            "¿De dónde creés que provienen las creencias limitantes o el juicio que sentís sobre tu propia vida sexual?",
            "¿Qué tipo de escenario mental te excita, aunque racionalmente sabés que nunca lo llevarías a cabo?",
            "¿Qué te asusta más: que tu pareja no se sienta satisfecha contigo o que descubra un deseo tuyo 'demasiado' intenso?",
            "Si tuvieras que definir tu 'estilo de apego' en lo íntimo (por ejemplo, ansioso, evitativo, seguro), ¿cuál sería y cómo afecta la conexión?"
        ]
    }
};

// ================= DATOS: RETOS EN PAREJA =================

const retosParejas = [
    "Vendá a tu pareja. Con tus labios, elegí una o varias partes de su cuerpo y hacé un recorrido suave durante",
    "Vendá a tu pareja. Con tu lengua, elegí una o varias partes de su cuerpo y hacé un recorrido suave durante",
    "Acercate a su oído y susurrale palabras que lo/la hagan sentir deseado/a… pero sin decir directamente qué querés. Solo insinuaciones, voz baja, respiración",
    "Tu pareja vendada. Ahora guiá sus manos hacia lugares que vos desees durante",
    "Trazá lentamente líneas sobre su piel con un solo dedo. Ella/él debe adivinar la forma (círculo, línea, corazón, etc.) durante",
    "Escribí una palabra en su espalda usando solo tus dedos. Si la adivina, guiá a tu pareja para que bese la parte que vos quieras durante",
    "En silencio total, solo usando gestos y toques suaves, indicá a tu pareja qué querés que haga. No se puede hablar. Si adivina lo debe interpretar. Consejo: no seas tan obvio/a. Regla: solo se permite por 2 segundos",
    "Tu pareja pasa sus partes, boca o manos, por donde quiera. Vos no te podés mover ni decir nada",
    "Tu pareja debe quedarse inmóvil durante el tiempo del reto, vos podés acercarte, rodearlo/a, tocar, provocar tensión… dejate llevar durante",
    "Ganaste un premio: recibís un masaje donde vos quieras durante",
    "Sexo oral espontáneo, elegí el lugar durante",
    "Sexo carnal espontáneo, elegí el lugar durante",
    "Hacé caricias intensas en espalda, cintura y cadera durante",
    "Gemí muy cerca de su cuello y oreja durante",
    "Usá tus nudillos para rozar zonas durante",
    "Guiá a tu pareja a adoptar una postura y tener sexo con ropa durante",
    "Bésalo intensamente. Tu pareja no puede reaccionar durante",
    "Acuesta a tu pareja y usá solo tu boca para explorar su cuerpo durante",
    "Acuesta a tu pareja y usá solo tus manos para explorar su cuerpo durante",
    "Acuesta a tu pareja y que te de Sexo oral durante",
    "Acuesta a tu pareja y dale Sexo carnal durante",
    "Escribí con saliva una fantasía que te gustaría intentar en la piel de tu pareja. Ella/él debe intentar descifrarla solo con el tacto antes de que se seque.",
    "Tu pareja elige una parte de tu cuerpo que sabe que te excita. Debe acercarse, hacer un gesto muy sensual (sin tocar) y alejarse, repitiendo esto varias veces durante el tiempo del reto.",
    "Aplicá un cubito de hielo o algo tibio sobre la piel de tu pareja en una zona erógena, alternando las temperaturas para crear un contraste sensorial intenso durante",
    "Contá un recuerdo íntimo compartido o una fantasía personal con el mayor detalle posible, sin tocar a tu pareja, usando solo el tono de voz y la expresión facial para excitarlo/a durante",
    "Vendá los ojos de tu pareja. Usá una pluma, seda o tus uñas (con cuidado) para rozar suavemente zonas NO erógenas (cuello, muñecas, espalda) antes de llegar al punto que realmente deseas tocar. Mantené la intriga durante"
];